name: Build and push image
on:
  push:
    branches: [disable]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: big-dipper
      PROJECT_ID: spair-api
      IMAGE_HOST: us.gcr.io
      IMAGE_PATH: fulldivevr
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: config docker client
      run: gcloud auth configure-docker --quiet

    - name: build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: push docker image to GCR
      env:
        TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest $IMAGE_HOST/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $IMAGE_HOST/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:$TAG
        docker push $IMAGE_HOST/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:latest
        docker push $IMAGE_HOST/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:$TAG
    - name: config helm
      run: |-
        helm repo add fulldive http://charts.fdvr.co
        helm repo add makeomatic http://charts.fdvr.co
