version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerfileInit
    ports:
      - '3080:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS: ${METEOR_SETTINGS}

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

#  mongodb:
#    image: bitnami/mongodb:4.4
#    ports:
#      - '27017:27017'
#    environment:
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_REPLICA_SET_NAME=rs0
#      - ALLOW_EMPTY_PASSWORD=yes
#    healthcheck:
#      test: 'mongo --eval "db.adminCommand(''ping'')" mongodb://localhost/local?replicaSet=rs0'
#      interval: 2s
#      timeout: 2s
#      retries: 30
#    logging:
#      driver: none
volumes:
  data:
