name: Build and push image
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: big-dipper
      PROJECT_ID: spair-api
      IMAGE_HOST: us.gcr.io
      IMAGE_PATH: fulldivevr
    container:
      image: us.gcr.io/spair-api/deploy/ci:7.0.0
      credentials:
        username: _json_key
        password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: build
        run: |
          - . configure
          - export APP_NAME=$(jq -r .name package.json)
          - export IMAGE_NAME=us.gcr.io/spair-api/fulldivevr/$APP_NAME
          - export COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          - export IMAGE_TAG=$IMAGE_NAME:$COMMIT_HASH
          - docker build -t $IMAGE_TAG .
          - docker push $IMAGE_TAG

      - name: print next step
        run: echo end=!!!!





