name: Build and push image
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    container:
      image: us.gcr.io/spair-api/deploy/ci:7.0.0
      credentials:
        username: _json_key
        password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        env:
          CLOUDSDK_API_KEY: ${{ secrets.CLOUDSDK_API_KEY }}
          CLOUDSDK_COMPUTE_ZONE: ${{ secrets.CLOUDSDK_COMPUTE_ZONE }}
          CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
          KUBERNETES_CLUSTER: ${{ secrets.KUBERNETES_CLUSTER }}
        run: |-
          . configure
          export APP_NAME=$(jq -r .name package.json)
          export IMAGE_NAME=us.gcr.io/spair-api/fulldivevr/$APP_NAME
          export COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          export IMAGE_TAG=$IMAGE_NAME:$COMMIT_HASH
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
        shell: bash

      - name: ENV
        run: env

      - name: print next step
        run: echo end=!!!!





